name: Deploy HR Microservice

on:
  push:
    branches:
      - master
    paths:
      - "src/hr/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # Build inside Docker containers
      - run: |
          cd ./src/hr
          sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - run: |
          cd ./src/hr
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
